export {default as AddBookmarkSVG} from "./AddBookmarkSVG.svg";
export {default as BookmarkSVG} from "./BookmarkSVG.svg";
export {default as LikeSelected} from "./LikeSelected.svg";
export {default as LikeUnselected} from "./LikeUnselected.svg";
export {default as DislikeSelected} from "./DislikeSelected.svg";
export {default as DislikeUnselected} from "./DislikeUnselected.svg";
export {default as EditSVG} from "./EditSVG.svg";
export {default as DeleteSVG} from "./DeleteSVG.svg";
export {default as ReportSVG} from "./ReportSVG.svg";